services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: market-ta-generator
    container_name: market-ta-generator
    restart: unless-stopped
    ports:
      - "8000:8000" # Maps host port 8000 to container port 8000
    env_file:
      - .env # Loads environment variables from .env file
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"] # Assumes app has a working root endpoint
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
