server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: container
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs: attrs
            time: time
      - json:
          expressions:
            tag: tag
          source: attrs
      - regex:
          expression: "/var/lib/docker/containers/(?P<container_id>[a-f0-9]{12})[a-f0-9]*/"
          source: filename
      - docker: {}
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_id:
      - output:
          source: output

  - job_name: persistent-app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: app-logs
          service: market-ta-generator
          source: persistent
          __path__: /logs/*.log

    pipeline_stages:
      - json: {}
      - timestamp:
          format: RFC3339Nano
          source: timestamp
      - labels:
          level:
          logger:
          module:
      - output:
          source: message

  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/syslog
